// Code generated by ent, DO NOT EDIT.

package modelcreditrate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelcreditrate type in the database.
	Label = "model_credit_rate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelPattern holds the string denoting the model_pattern field in the database.
	FieldModelPattern = "model_pattern"
	// FieldCreditsPer1kTokensInput holds the string denoting the credits_per_1k_tokens_input field in the database.
	FieldCreditsPer1kTokensInput = "credits_per_1k_tokens_input"
	// FieldCreditsPer1kTokensOutput holds the string denoting the credits_per_1k_tokens_output field in the database.
	FieldCreditsPer1kTokensOutput = "credits_per_1k_tokens_output"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelcreditrate in the database.
	Table = "model_credit_rates"
)

// Columns holds all SQL columns for modelcreditrate fields.
var Columns = []string{
	FieldID,
	FieldModelPattern,
	FieldCreditsPer1kTokensInput,
	FieldCreditsPer1kTokensOutput,
	FieldPriority,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelPatternValidator is a validator for the "model_pattern" field. It is called by the builders before save.
	ModelPatternValidator func(string) error
	// DefaultCreditsPer1kTokensInput holds the default value on creation for the "credits_per_1k_tokens_input" field.
	DefaultCreditsPer1kTokensInput int64
	// DefaultCreditsPer1kTokensOutput holds the default value on creation for the "credits_per_1k_tokens_output" field.
	DefaultCreditsPer1kTokensOutput int64
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelCreditRate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelPattern orders the results by the model_pattern field.
func ByModelPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelPattern, opts...).ToFunc()
}

// ByCreditsPer1kTokensInput orders the results by the credits_per_1k_tokens_input field.
func ByCreditsPer1kTokensInput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditsPer1kTokensInput, opts...).ToFunc()
}

// ByCreditsPer1kTokensOutput orders the results by the credits_per_1k_tokens_output field.
func ByCreditsPer1kTokensOutput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditsPer1kTokensOutput, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
