// Code generated by ent, DO NOT EDIT.

package modelcreditrate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldID, id))
}

// ModelPattern applies equality check predicate on the "model_pattern" field. It's identical to ModelPatternEQ.
func ModelPattern(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldModelPattern, v))
}

// CreditsPer1kTokensInput applies equality check predicate on the "credits_per_1k_tokens_input" field. It's identical to CreditsPer1kTokensInputEQ.
func CreditsPer1kTokensInput(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensOutput applies equality check predicate on the "credits_per_1k_tokens_output" field. It's identical to CreditsPer1kTokensOutputEQ.
func CreditsPer1kTokensOutput(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldCreditsPer1kTokensOutput, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldPriority, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelPatternEQ applies the EQ predicate on the "model_pattern" field.
func ModelPatternEQ(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldModelPattern, v))
}

// ModelPatternNEQ applies the NEQ predicate on the "model_pattern" field.
func ModelPatternNEQ(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldModelPattern, v))
}

// ModelPatternIn applies the In predicate on the "model_pattern" field.
func ModelPatternIn(vs ...string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldModelPattern, vs...))
}

// ModelPatternNotIn applies the NotIn predicate on the "model_pattern" field.
func ModelPatternNotIn(vs ...string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldModelPattern, vs...))
}

// ModelPatternGT applies the GT predicate on the "model_pattern" field.
func ModelPatternGT(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldModelPattern, v))
}

// ModelPatternGTE applies the GTE predicate on the "model_pattern" field.
func ModelPatternGTE(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldModelPattern, v))
}

// ModelPatternLT applies the LT predicate on the "model_pattern" field.
func ModelPatternLT(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldModelPattern, v))
}

// ModelPatternLTE applies the LTE predicate on the "model_pattern" field.
func ModelPatternLTE(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldModelPattern, v))
}

// ModelPatternContains applies the Contains predicate on the "model_pattern" field.
func ModelPatternContains(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldContains(FieldModelPattern, v))
}

// ModelPatternHasPrefix applies the HasPrefix predicate on the "model_pattern" field.
func ModelPatternHasPrefix(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldHasPrefix(FieldModelPattern, v))
}

// ModelPatternHasSuffix applies the HasSuffix predicate on the "model_pattern" field.
func ModelPatternHasSuffix(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldHasSuffix(FieldModelPattern, v))
}

// ModelPatternEqualFold applies the EqualFold predicate on the "model_pattern" field.
func ModelPatternEqualFold(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEqualFold(FieldModelPattern, v))
}

// ModelPatternContainsFold applies the ContainsFold predicate on the "model_pattern" field.
func ModelPatternContainsFold(v string) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldContainsFold(FieldModelPattern, v))
}

// CreditsPer1kTokensInputEQ applies the EQ predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputEQ(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensInputNEQ applies the NEQ predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputNEQ(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensInputIn applies the In predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputIn(vs ...int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldCreditsPer1kTokensInput, vs...))
}

// CreditsPer1kTokensInputNotIn applies the NotIn predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputNotIn(vs ...int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldCreditsPer1kTokensInput, vs...))
}

// CreditsPer1kTokensInputGT applies the GT predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputGT(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensInputGTE applies the GTE predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputGTE(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensInputLT applies the LT predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputLT(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensInputLTE applies the LTE predicate on the "credits_per_1k_tokens_input" field.
func CreditsPer1kTokensInputLTE(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldCreditsPer1kTokensInput, v))
}

// CreditsPer1kTokensOutputEQ applies the EQ predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputEQ(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldCreditsPer1kTokensOutput, v))
}

// CreditsPer1kTokensOutputNEQ applies the NEQ predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputNEQ(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldCreditsPer1kTokensOutput, v))
}

// CreditsPer1kTokensOutputIn applies the In predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputIn(vs ...int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldCreditsPer1kTokensOutput, vs...))
}

// CreditsPer1kTokensOutputNotIn applies the NotIn predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputNotIn(vs ...int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldCreditsPer1kTokensOutput, vs...))
}

// CreditsPer1kTokensOutputGT applies the GT predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputGT(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldCreditsPer1kTokensOutput, v))
}

// CreditsPer1kTokensOutputGTE applies the GTE predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputGTE(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldCreditsPer1kTokensOutput, v))
}

// CreditsPer1kTokensOutputLT applies the LT predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputLT(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldCreditsPer1kTokensOutput, v))
}

// CreditsPer1kTokensOutputLTE applies the LTE predicate on the "credits_per_1k_tokens_output" field.
func CreditsPer1kTokensOutputLTE(v int64) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldCreditsPer1kTokensOutput, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldPriority, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelCreditRate) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelCreditRate) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelCreditRate) predicate.ModelCreditRate {
	return predicate.ModelCreditRate(sql.NotPredicates(p))
}
