// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creditledger"
)

// CreditLedgerCreate is the builder for creating a CreditLedger entity.
type CreditLedgerCreate struct {
	config
	mutation *CreditLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CreditLedgerCreate) SetUserID(v int64) *CreditLedgerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDelta sets the "delta" field.
func (_c *CreditLedgerCreate) SetDelta(v int64) *CreditLedgerCreate {
	_c.mutation.SetDelta(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *CreditLedgerCreate) SetReason(v string) *CreditLedgerCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetRefID sets the "ref_id" field.
func (_c *CreditLedgerCreate) SetRefID(v string) *CreditLedgerCreate {
	_c.mutation.SetRefID(v)
	return _c
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_c *CreditLedgerCreate) SetNillableRefID(v *string) *CreditLedgerCreate {
	if v != nil {
		_c.SetRefID(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *CreditLedgerCreate) SetBalanceAfter(v int64) *CreditLedgerCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *CreditLedgerCreate) SetModel(v string) *CreditLedgerCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *CreditLedgerCreate) SetNillableModel(v *string) *CreditLedgerCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreditLedgerCreate) SetCreatedAt(v time.Time) *CreditLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreditLedgerCreate) SetNillableCreatedAt(v *time.Time) *CreditLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CreditLedgerMutation object of the builder.
func (_c *CreditLedgerCreate) Mutation() *CreditLedgerMutation {
	return _c.mutation
}

// Save creates the CreditLedger in the database.
func (_c *CreditLedgerCreate) Save(ctx context.Context) (*CreditLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreditLedgerCreate) SaveX(ctx context.Context) *CreditLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreditLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creditledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreditLedgerCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CreditLedger.user_id"`)}
	}
	if _, ok := _c.mutation.Delta(); !ok {
		return &ValidationError{Name: "delta", err: errors.New(`ent: missing required field "CreditLedger.delta"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "CreditLedger.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := creditledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RefID(); ok {
		if err := creditledger.RefIDValidator(v); err != nil {
			return &ValidationError{Name: "ref_id", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.ref_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "CreditLedger.balance_after"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := creditledger.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreditLedger.created_at"`)}
	}
	return nil
}

func (_c *CreditLedgerCreate) sqlSave(ctx context.Context) (*CreditLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreditLedgerCreate) createSpec() (*CreditLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creditledger.Table, sqlgraph.NewFieldSpec(creditledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(creditledger.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Delta(); ok {
		_spec.SetField(creditledger.FieldDelta, field.TypeInt64, value)
		_node.Delta = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(creditledger.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.RefID(); ok {
		_spec.SetField(creditledger.FieldRefID, field.TypeString, value)
		_node.RefID = &value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(creditledger.FieldBalanceAfter, field.TypeInt64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(creditledger.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creditledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditLedger.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditLedgerCreate) OnConflict(opts ...sql.ConflictOption) *CreditLedgerUpsertOne {
	_c.conflict = opts
	return &CreditLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditLedgerCreate) OnConflictColumns(columns ...string) *CreditLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditLedgerUpsertOne{
		create: _c,
	}
}

type (
	// CreditLedgerUpsertOne is the builder for "upsert"-ing
	//  one CreditLedger node.
	CreditLedgerUpsertOne struct {
		create *CreditLedgerCreate
	}

	// CreditLedgerUpsert is the "OnConflict" setter.
	CreditLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CreditLedgerUpsert) SetUserID(v int64) *CreditLedgerUpsert {
	u.Set(creditledger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreditLedgerUpsert) UpdateUserID() *CreditLedgerUpsert {
	u.SetExcluded(creditledger.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CreditLedgerUpsert) AddUserID(v int64) *CreditLedgerUpsert {
	u.Add(creditledger.FieldUserID, v)
	return u
}

// SetDelta sets the "delta" field.
func (u *CreditLedgerUpsert) SetDelta(v int64) *CreditLedgerUpsert {
	u.Set(creditledger.FieldDelta, v)
	return u
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *CreditLedgerUpsert) UpdateDelta() *CreditLedgerUpsert {
	u.SetExcluded(creditledger.FieldDelta)
	return u
}

// AddDelta adds v to the "delta" field.
func (u *CreditLedgerUpsert) AddDelta(v int64) *CreditLedgerUpsert {
	u.Add(creditledger.FieldDelta, v)
	return u
}

// SetReason sets the "reason" field.
func (u *CreditLedgerUpsert) SetReason(v string) *CreditLedgerUpsert {
	u.Set(creditledger.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *CreditLedgerUpsert) UpdateReason() *CreditLedgerUpsert {
	u.SetExcluded(creditledger.FieldReason)
	return u
}

// SetRefID sets the "ref_id" field.
func (u *CreditLedgerUpsert) SetRefID(v string) *CreditLedgerUpsert {
	u.Set(creditledger.FieldRefID, v)
	return u
}

// UpdateRefID sets the "ref_id" field to the value that was provided on create.
func (u *CreditLedgerUpsert) UpdateRefID() *CreditLedgerUpsert {
	u.SetExcluded(creditledger.FieldRefID)
	return u
}

// ClearRefID clears the value of the "ref_id" field.
func (u *CreditLedgerUpsert) ClearRefID() *CreditLedgerUpsert {
	u.SetNull(creditledger.FieldRefID)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *CreditLedgerUpsert) SetBalanceAfter(v int64) *CreditLedgerUpsert {
	u.Set(creditledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *CreditLedgerUpsert) UpdateBalanceAfter() *CreditLedgerUpsert {
	u.SetExcluded(creditledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *CreditLedgerUpsert) AddBalanceAfter(v int64) *CreditLedgerUpsert {
	u.Add(creditledger.FieldBalanceAfter, v)
	return u
}

// SetModel sets the "model" field.
func (u *CreditLedgerUpsert) SetModel(v string) *CreditLedgerUpsert {
	u.Set(creditledger.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreditLedgerUpsert) UpdateModel() *CreditLedgerUpsert {
	u.SetExcluded(creditledger.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *CreditLedgerUpsert) ClearModel() *CreditLedgerUpsert {
	u.SetNull(creditledger.FieldModel)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CreditLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreditLedgerUpsertOne) UpdateNewValues() *CreditLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creditledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreditLedgerUpsertOne) Ignore() *CreditLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditLedgerUpsertOne) DoNothing() *CreditLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditLedgerCreate.OnConflict
// documentation for more info.
func (u *CreditLedgerUpsertOne) Update(set func(*CreditLedgerUpsert)) *CreditLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CreditLedgerUpsertOne) SetUserID(v int64) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CreditLedgerUpsertOne) AddUserID(v int64) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreditLedgerUpsertOne) UpdateUserID() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetDelta sets the "delta" field.
func (u *CreditLedgerUpsertOne) SetDelta(v int64) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetDelta(v)
	})
}

// AddDelta adds v to the "delta" field.
func (u *CreditLedgerUpsertOne) AddDelta(v int64) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.AddDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *CreditLedgerUpsertOne) UpdateDelta() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateDelta()
	})
}

// SetReason sets the "reason" field.
func (u *CreditLedgerUpsertOne) SetReason(v string) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *CreditLedgerUpsertOne) UpdateReason() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetRefID sets the "ref_id" field.
func (u *CreditLedgerUpsertOne) SetRefID(v string) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetRefID(v)
	})
}

// UpdateRefID sets the "ref_id" field to the value that was provided on create.
func (u *CreditLedgerUpsertOne) UpdateRefID() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateRefID()
	})
}

// ClearRefID clears the value of the "ref_id" field.
func (u *CreditLedgerUpsertOne) ClearRefID() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.ClearRefID()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *CreditLedgerUpsertOne) SetBalanceAfter(v int64) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *CreditLedgerUpsertOne) AddBalanceAfter(v int64) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *CreditLedgerUpsertOne) UpdateBalanceAfter() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetModel sets the "model" field.
func (u *CreditLedgerUpsertOne) SetModel(v string) *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreditLedgerUpsertOne) UpdateModel() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *CreditLedgerUpsertOne) ClearModel() *CreditLedgerUpsertOne {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.ClearModel()
	})
}

// Exec executes the query.
func (u *CreditLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreditLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreditLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreditLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreditLedgerCreateBulk is the builder for creating many CreditLedger entities in bulk.
type CreditLedgerCreateBulk struct {
	config
	err      error
	builders []*CreditLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the CreditLedger entities in the database.
func (_c *CreditLedgerCreateBulk) Save(ctx context.Context) ([]*CreditLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreditLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreditLedgerCreateBulk) SaveX(ctx context.Context) []*CreditLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreditLedgerUpsertBulk {
	_c.conflict = opts
	return &CreditLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditLedgerCreateBulk) OnConflictColumns(columns ...string) *CreditLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditLedgerUpsertBulk{
		create: _c,
	}
}

// CreditLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of CreditLedger nodes.
type CreditLedgerUpsertBulk struct {
	create *CreditLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreditLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreditLedgerUpsertBulk) UpdateNewValues() *CreditLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creditledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreditLedgerUpsertBulk) Ignore() *CreditLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditLedgerUpsertBulk) DoNothing() *CreditLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *CreditLedgerUpsertBulk) Update(set func(*CreditLedgerUpsert)) *CreditLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CreditLedgerUpsertBulk) SetUserID(v int64) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CreditLedgerUpsertBulk) AddUserID(v int64) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreditLedgerUpsertBulk) UpdateUserID() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetDelta sets the "delta" field.
func (u *CreditLedgerUpsertBulk) SetDelta(v int64) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetDelta(v)
	})
}

// AddDelta adds v to the "delta" field.
func (u *CreditLedgerUpsertBulk) AddDelta(v int64) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.AddDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *CreditLedgerUpsertBulk) UpdateDelta() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateDelta()
	})
}

// SetReason sets the "reason" field.
func (u *CreditLedgerUpsertBulk) SetReason(v string) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *CreditLedgerUpsertBulk) UpdateReason() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetRefID sets the "ref_id" field.
func (u *CreditLedgerUpsertBulk) SetRefID(v string) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetRefID(v)
	})
}

// UpdateRefID sets the "ref_id" field to the value that was provided on create.
func (u *CreditLedgerUpsertBulk) UpdateRefID() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateRefID()
	})
}

// ClearRefID clears the value of the "ref_id" field.
func (u *CreditLedgerUpsertBulk) ClearRefID() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.ClearRefID()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *CreditLedgerUpsertBulk) SetBalanceAfter(v int64) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *CreditLedgerUpsertBulk) AddBalanceAfter(v int64) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *CreditLedgerUpsertBulk) UpdateBalanceAfter() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetModel sets the "model" field.
func (u *CreditLedgerUpsertBulk) SetModel(v string) *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreditLedgerUpsertBulk) UpdateModel() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *CreditLedgerUpsertBulk) ClearModel() *CreditLedgerUpsertBulk {
	return u.Update(func(s *CreditLedgerUpsert) {
		s.ClearModel()
	})
}

// Exec executes the query.
func (u *CreditLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreditLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreditLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
