// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/creditledger"
)

// CreditLedger is the model entity for the CreditLedger schema.
type CreditLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 关联用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 积分变动量，正数为充值，负数为消耗
	Delta int64 `json:"delta,omitempty"`
	// 变动原因：purchase | api_call | admin_grant | expiry_reset
	Reason string `json:"reason,omitempty"`
	// 关联记录 ID，如订单 ID 或请求 ID
	RefID *string `json:"ref_id,omitempty"`
	// 操作后的余额快照
	BalanceAfter int64 `json:"balance_after,omitempty"`
	// 消耗时的模型名称，reason=api_call 时填写
	Model *string `json:"model,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creditledger.FieldID, creditledger.FieldUserID, creditledger.FieldDelta, creditledger.FieldBalanceAfter:
			values[i] = new(sql.NullInt64)
		case creditledger.FieldReason, creditledger.FieldRefID, creditledger.FieldModel:
			values[i] = new(sql.NullString)
		case creditledger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditLedger fields.
func (_m *CreditLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creditledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case creditledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case creditledger.FieldDelta:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delta", values[i])
			} else if value.Valid {
				_m.Delta = value.Int64
			}
		case creditledger.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case creditledger.FieldRefID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_id", values[i])
			} else if value.Valid {
				_m.RefID = new(string)
				*_m.RefID = value.String
			}
		case creditledger.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Int64
			}
		case creditledger.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case creditledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditLedger.
// This includes values selected through modifiers, order, etc.
func (_m *CreditLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CreditLedger.
// Note that you need to call CreditLedger.Unwrap() before calling this method if this CreditLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreditLedger) Update() *CreditLedgerUpdateOne {
	return NewCreditLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreditLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreditLedger) Unwrap() *CreditLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreditLedger) String() string {
	var builder strings.Builder
	builder.WriteString("CreditLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.Delta))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.RefID; v != nil {
		builder.WriteString("ref_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CreditLedgers is a parsable slice of CreditLedger.
type CreditLedgers []*CreditLedger
