// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creditledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CreditLedgerUpdate is the builder for updating CreditLedger entities.
type CreditLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *CreditLedgerMutation
}

// Where appends a list predicates to the CreditLedgerUpdate builder.
func (_u *CreditLedgerUpdate) Where(ps ...predicate.CreditLedger) *CreditLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CreditLedgerUpdate) SetUserID(v int64) *CreditLedgerUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CreditLedgerUpdate) SetNillableUserID(v *int64) *CreditLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CreditLedgerUpdate) AddUserID(v int64) *CreditLedgerUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDelta sets the "delta" field.
func (_u *CreditLedgerUpdate) SetDelta(v int64) *CreditLedgerUpdate {
	_u.mutation.ResetDelta()
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *CreditLedgerUpdate) SetNillableDelta(v *int64) *CreditLedgerUpdate {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// AddDelta adds value to the "delta" field.
func (_u *CreditLedgerUpdate) AddDelta(v int64) *CreditLedgerUpdate {
	_u.mutation.AddDelta(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *CreditLedgerUpdate) SetReason(v string) *CreditLedgerUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CreditLedgerUpdate) SetNillableReason(v *string) *CreditLedgerUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *CreditLedgerUpdate) SetRefID(v string) *CreditLedgerUpdate {
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *CreditLedgerUpdate) SetNillableRefID(v *string) *CreditLedgerUpdate {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// ClearRefID clears the value of the "ref_id" field.
func (_u *CreditLedgerUpdate) ClearRefID() *CreditLedgerUpdate {
	_u.mutation.ClearRefID()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *CreditLedgerUpdate) SetBalanceAfter(v int64) *CreditLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *CreditLedgerUpdate) SetNillableBalanceAfter(v *int64) *CreditLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *CreditLedgerUpdate) AddBalanceAfter(v int64) *CreditLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *CreditLedgerUpdate) SetModel(v string) *CreditLedgerUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CreditLedgerUpdate) SetNillableModel(v *string) *CreditLedgerUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *CreditLedgerUpdate) ClearModel() *CreditLedgerUpdate {
	_u.mutation.ClearModel()
	return _u
}

// Mutation returns the CreditLedgerMutation object of the builder.
func (_u *CreditLedgerUpdate) Mutation() *CreditLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CreditLedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreditLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CreditLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreditLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreditLedgerUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := creditledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefID(); ok {
		if err := creditledger.RefIDValidator(v); err != nil {
			return &ValidationError{Name: "ref_id", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.ref_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := creditledger.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.model": %w`, err)}
		}
	}
	return nil
}

func (_u *CreditLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creditledger.Table, creditledger.Columns, sqlgraph.NewFieldSpec(creditledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(creditledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(creditledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(creditledger.FieldDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDelta(); ok {
		_spec.AddField(creditledger.FieldDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(creditledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(creditledger.FieldRefID, field.TypeString, value)
	}
	if _u.mutation.RefIDCleared() {
		_spec.ClearField(creditledger.FieldRefID, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(creditledger.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(creditledger.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(creditledger.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(creditledger.FieldModel, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creditledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CreditLedgerUpdateOne is the builder for updating a single CreditLedger entity.
type CreditLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreditLedgerMutation
}

// SetUserID sets the "user_id" field.
func (_u *CreditLedgerUpdateOne) SetUserID(v int64) *CreditLedgerUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CreditLedgerUpdateOne) SetNillableUserID(v *int64) *CreditLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CreditLedgerUpdateOne) AddUserID(v int64) *CreditLedgerUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDelta sets the "delta" field.
func (_u *CreditLedgerUpdateOne) SetDelta(v int64) *CreditLedgerUpdateOne {
	_u.mutation.ResetDelta()
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *CreditLedgerUpdateOne) SetNillableDelta(v *int64) *CreditLedgerUpdateOne {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// AddDelta adds value to the "delta" field.
func (_u *CreditLedgerUpdateOne) AddDelta(v int64) *CreditLedgerUpdateOne {
	_u.mutation.AddDelta(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *CreditLedgerUpdateOne) SetReason(v string) *CreditLedgerUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CreditLedgerUpdateOne) SetNillableReason(v *string) *CreditLedgerUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *CreditLedgerUpdateOne) SetRefID(v string) *CreditLedgerUpdateOne {
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *CreditLedgerUpdateOne) SetNillableRefID(v *string) *CreditLedgerUpdateOne {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// ClearRefID clears the value of the "ref_id" field.
func (_u *CreditLedgerUpdateOne) ClearRefID() *CreditLedgerUpdateOne {
	_u.mutation.ClearRefID()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *CreditLedgerUpdateOne) SetBalanceAfter(v int64) *CreditLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *CreditLedgerUpdateOne) SetNillableBalanceAfter(v *int64) *CreditLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *CreditLedgerUpdateOne) AddBalanceAfter(v int64) *CreditLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *CreditLedgerUpdateOne) SetModel(v string) *CreditLedgerUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CreditLedgerUpdateOne) SetNillableModel(v *string) *CreditLedgerUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *CreditLedgerUpdateOne) ClearModel() *CreditLedgerUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// Mutation returns the CreditLedgerMutation object of the builder.
func (_u *CreditLedgerUpdateOne) Mutation() *CreditLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the CreditLedgerUpdate builder.
func (_u *CreditLedgerUpdateOne) Where(ps ...predicate.CreditLedger) *CreditLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CreditLedgerUpdateOne) Select(field string, fields ...string) *CreditLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CreditLedger entity.
func (_u *CreditLedgerUpdateOne) Save(ctx context.Context) (*CreditLedger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreditLedgerUpdateOne) SaveX(ctx context.Context) *CreditLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CreditLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreditLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreditLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := creditledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefID(); ok {
		if err := creditledger.RefIDValidator(v); err != nil {
			return &ValidationError{Name: "ref_id", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.ref_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := creditledger.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreditLedger.model": %w`, err)}
		}
	}
	return nil
}

func (_u *CreditLedgerUpdateOne) sqlSave(ctx context.Context) (_node *CreditLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creditledger.Table, creditledger.Columns, sqlgraph.NewFieldSpec(creditledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreditLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creditledger.FieldID)
		for _, f := range fields {
			if !creditledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creditledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(creditledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(creditledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(creditledger.FieldDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDelta(); ok {
		_spec.AddField(creditledger.FieldDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(creditledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(creditledger.FieldRefID, field.TypeString, value)
	}
	if _u.mutation.RefIDCleared() {
		_spec.ClearField(creditledger.FieldRefID, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(creditledger.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(creditledger.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(creditledger.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(creditledger.FieldModel, field.TypeString)
	}
	_node = &CreditLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creditledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
