// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcreditrate"
)

// ModelCreditRateCreate is the builder for creating a ModelCreditRate entity.
type ModelCreditRateCreate struct {
	config
	mutation *ModelCreditRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelPattern sets the "model_pattern" field.
func (_c *ModelCreditRateCreate) SetModelPattern(v string) *ModelCreditRateCreate {
	_c.mutation.SetModelPattern(v)
	return _c
}

// SetCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field.
func (_c *ModelCreditRateCreate) SetCreditsPer1kTokensInput(v int64) *ModelCreditRateCreate {
	_c.mutation.SetCreditsPer1kTokensInput(v)
	return _c
}

// SetNillableCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field if the given value is not nil.
func (_c *ModelCreditRateCreate) SetNillableCreditsPer1kTokensInput(v *int64) *ModelCreditRateCreate {
	if v != nil {
		_c.SetCreditsPer1kTokensInput(*v)
	}
	return _c
}

// SetCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field.
func (_c *ModelCreditRateCreate) SetCreditsPer1kTokensOutput(v int64) *ModelCreditRateCreate {
	_c.mutation.SetCreditsPer1kTokensOutput(v)
	return _c
}

// SetNillableCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field if the given value is not nil.
func (_c *ModelCreditRateCreate) SetNillableCreditsPer1kTokensOutput(v *int64) *ModelCreditRateCreate {
	if v != nil {
		_c.SetCreditsPer1kTokensOutput(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ModelCreditRateCreate) SetPriority(v int) *ModelCreditRateCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ModelCreditRateCreate) SetNillablePriority(v *int) *ModelCreditRateCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCreditRateCreate) SetCreatedAt(v time.Time) *ModelCreditRateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCreditRateCreate) SetNillableCreatedAt(v *time.Time) *ModelCreditRateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCreditRateCreate) SetUpdatedAt(v time.Time) *ModelCreditRateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCreditRateCreate) SetNillableUpdatedAt(v *time.Time) *ModelCreditRateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ModelCreditRateMutation object of the builder.
func (_c *ModelCreditRateCreate) Mutation() *ModelCreditRateMutation {
	return _c.mutation
}

// Save creates the ModelCreditRate in the database.
func (_c *ModelCreditRateCreate) Save(ctx context.Context) (*ModelCreditRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCreditRateCreate) SaveX(ctx context.Context) *ModelCreditRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCreditRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCreditRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCreditRateCreate) defaults() {
	if _, ok := _c.mutation.CreditsPer1kTokensInput(); !ok {
		v := modelcreditrate.DefaultCreditsPer1kTokensInput
		_c.mutation.SetCreditsPer1kTokensInput(v)
	}
	if _, ok := _c.mutation.CreditsPer1kTokensOutput(); !ok {
		v := modelcreditrate.DefaultCreditsPer1kTokensOutput
		_c.mutation.SetCreditsPer1kTokensOutput(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := modelcreditrate.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcreditrate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcreditrate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCreditRateCreate) check() error {
	if _, ok := _c.mutation.ModelPattern(); !ok {
		return &ValidationError{Name: "model_pattern", err: errors.New(`ent: missing required field "ModelCreditRate.model_pattern"`)}
	}
	if v, ok := _c.mutation.ModelPattern(); ok {
		if err := modelcreditrate.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelCreditRate.model_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditsPer1kTokensInput(); !ok {
		return &ValidationError{Name: "credits_per_1k_tokens_input", err: errors.New(`ent: missing required field "ModelCreditRate.credits_per_1k_tokens_input"`)}
	}
	if _, ok := _c.mutation.CreditsPer1kTokensOutput(); !ok {
		return &ValidationError{Name: "credits_per_1k_tokens_output", err: errors.New(`ent: missing required field "ModelCreditRate.credits_per_1k_tokens_output"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "ModelCreditRate.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCreditRate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCreditRate.updated_at"`)}
	}
	return nil
}

func (_c *ModelCreditRateCreate) sqlSave(ctx context.Context) (*ModelCreditRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCreditRateCreate) createSpec() (*ModelCreditRate, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCreditRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcreditrate.Table, sqlgraph.NewFieldSpec(modelcreditrate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelPattern(); ok {
		_spec.SetField(modelcreditrate.FieldModelPattern, field.TypeString, value)
		_node.ModelPattern = value
	}
	if value, ok := _c.mutation.CreditsPer1kTokensInput(); ok {
		_spec.SetField(modelcreditrate.FieldCreditsPer1kTokensInput, field.TypeInt64, value)
		_node.CreditsPer1kTokensInput = value
	}
	if value, ok := _c.mutation.CreditsPer1kTokensOutput(); ok {
		_spec.SetField(modelcreditrate.FieldCreditsPer1kTokensOutput, field.TypeInt64, value)
		_node.CreditsPer1kTokensOutput = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(modelcreditrate.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcreditrate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcreditrate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCreditRate.Create().
//		SetModelPattern(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCreditRateUpsert) {
//			SetModelPattern(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCreditRateCreate) OnConflict(opts ...sql.ConflictOption) *ModelCreditRateUpsertOne {
	_c.conflict = opts
	return &ModelCreditRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCreditRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCreditRateCreate) OnConflictColumns(columns ...string) *ModelCreditRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCreditRateUpsertOne{
		create: _c,
	}
}

type (
	// ModelCreditRateUpsertOne is the builder for "upsert"-ing
	//  one ModelCreditRate node.
	ModelCreditRateUpsertOne struct {
		create *ModelCreditRateCreate
	}

	// ModelCreditRateUpsert is the "OnConflict" setter.
	ModelCreditRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelPattern sets the "model_pattern" field.
func (u *ModelCreditRateUpsert) SetModelPattern(v string) *ModelCreditRateUpsert {
	u.Set(modelcreditrate.FieldModelPattern, v)
	return u
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *ModelCreditRateUpsert) UpdateModelPattern() *ModelCreditRateUpsert {
	u.SetExcluded(modelcreditrate.FieldModelPattern)
	return u
}

// SetCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field.
func (u *ModelCreditRateUpsert) SetCreditsPer1kTokensInput(v int64) *ModelCreditRateUpsert {
	u.Set(modelcreditrate.FieldCreditsPer1kTokensInput, v)
	return u
}

// UpdateCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field to the value that was provided on create.
func (u *ModelCreditRateUpsert) UpdateCreditsPer1kTokensInput() *ModelCreditRateUpsert {
	u.SetExcluded(modelcreditrate.FieldCreditsPer1kTokensInput)
	return u
}

// AddCreditsPer1kTokensInput adds v to the "credits_per_1k_tokens_input" field.
func (u *ModelCreditRateUpsert) AddCreditsPer1kTokensInput(v int64) *ModelCreditRateUpsert {
	u.Add(modelcreditrate.FieldCreditsPer1kTokensInput, v)
	return u
}

// SetCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field.
func (u *ModelCreditRateUpsert) SetCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpsert {
	u.Set(modelcreditrate.FieldCreditsPer1kTokensOutput, v)
	return u
}

// UpdateCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field to the value that was provided on create.
func (u *ModelCreditRateUpsert) UpdateCreditsPer1kTokensOutput() *ModelCreditRateUpsert {
	u.SetExcluded(modelcreditrate.FieldCreditsPer1kTokensOutput)
	return u
}

// AddCreditsPer1kTokensOutput adds v to the "credits_per_1k_tokens_output" field.
func (u *ModelCreditRateUpsert) AddCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpsert {
	u.Add(modelcreditrate.FieldCreditsPer1kTokensOutput, v)
	return u
}

// SetPriority sets the "priority" field.
func (u *ModelCreditRateUpsert) SetPriority(v int) *ModelCreditRateUpsert {
	u.Set(modelcreditrate.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ModelCreditRateUpsert) UpdatePriority() *ModelCreditRateUpsert {
	u.SetExcluded(modelcreditrate.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *ModelCreditRateUpsert) AddPriority(v int) *ModelCreditRateUpsert {
	u.Add(modelcreditrate.FieldPriority, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCreditRateUpsert) SetUpdatedAt(v time.Time) *ModelCreditRateUpsert {
	u.Set(modelcreditrate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCreditRateUpsert) UpdateUpdatedAt() *ModelCreditRateUpsert {
	u.SetExcluded(modelcreditrate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelCreditRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCreditRateUpsertOne) UpdateNewValues() *ModelCreditRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelcreditrate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCreditRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelCreditRateUpsertOne) Ignore() *ModelCreditRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCreditRateUpsertOne) DoNothing() *ModelCreditRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCreditRateCreate.OnConflict
// documentation for more info.
func (u *ModelCreditRateUpsertOne) Update(set func(*ModelCreditRateUpsert)) *ModelCreditRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCreditRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *ModelCreditRateUpsertOne) SetModelPattern(v string) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *ModelCreditRateUpsertOne) UpdateModelPattern() *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateModelPattern()
	})
}

// SetCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field.
func (u *ModelCreditRateUpsertOne) SetCreditsPer1kTokensInput(v int64) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetCreditsPer1kTokensInput(v)
	})
}

// AddCreditsPer1kTokensInput adds v to the "credits_per_1k_tokens_input" field.
func (u *ModelCreditRateUpsertOne) AddCreditsPer1kTokensInput(v int64) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.AddCreditsPer1kTokensInput(v)
	})
}

// UpdateCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field to the value that was provided on create.
func (u *ModelCreditRateUpsertOne) UpdateCreditsPer1kTokensInput() *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateCreditsPer1kTokensInput()
	})
}

// SetCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field.
func (u *ModelCreditRateUpsertOne) SetCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetCreditsPer1kTokensOutput(v)
	})
}

// AddCreditsPer1kTokensOutput adds v to the "credits_per_1k_tokens_output" field.
func (u *ModelCreditRateUpsertOne) AddCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.AddCreditsPer1kTokensOutput(v)
	})
}

// UpdateCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field to the value that was provided on create.
func (u *ModelCreditRateUpsertOne) UpdateCreditsPer1kTokensOutput() *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateCreditsPer1kTokensOutput()
	})
}

// SetPriority sets the "priority" field.
func (u *ModelCreditRateUpsertOne) SetPriority(v int) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ModelCreditRateUpsertOne) AddPriority(v int) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ModelCreditRateUpsertOne) UpdatePriority() *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdatePriority()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCreditRateUpsertOne) SetUpdatedAt(v time.Time) *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCreditRateUpsertOne) UpdateUpdatedAt() *ModelCreditRateUpsertOne {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelCreditRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCreditRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCreditRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelCreditRateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelCreditRateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelCreditRateCreateBulk is the builder for creating many ModelCreditRate entities in bulk.
type ModelCreditRateCreateBulk struct {
	config
	err      error
	builders []*ModelCreditRateCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelCreditRate entities in the database.
func (_c *ModelCreditRateCreateBulk) Save(ctx context.Context) ([]*ModelCreditRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCreditRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCreditRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCreditRateCreateBulk) SaveX(ctx context.Context) []*ModelCreditRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCreditRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCreditRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCreditRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCreditRateUpsert) {
//			SetModelPattern(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCreditRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelCreditRateUpsertBulk {
	_c.conflict = opts
	return &ModelCreditRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCreditRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCreditRateCreateBulk) OnConflictColumns(columns ...string) *ModelCreditRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCreditRateUpsertBulk{
		create: _c,
	}
}

// ModelCreditRateUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelCreditRate nodes.
type ModelCreditRateUpsertBulk struct {
	create *ModelCreditRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelCreditRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCreditRateUpsertBulk) UpdateNewValues() *ModelCreditRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelcreditrate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCreditRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelCreditRateUpsertBulk) Ignore() *ModelCreditRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCreditRateUpsertBulk) DoNothing() *ModelCreditRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCreditRateCreateBulk.OnConflict
// documentation for more info.
func (u *ModelCreditRateUpsertBulk) Update(set func(*ModelCreditRateUpsert)) *ModelCreditRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCreditRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *ModelCreditRateUpsertBulk) SetModelPattern(v string) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *ModelCreditRateUpsertBulk) UpdateModelPattern() *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateModelPattern()
	})
}

// SetCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field.
func (u *ModelCreditRateUpsertBulk) SetCreditsPer1kTokensInput(v int64) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetCreditsPer1kTokensInput(v)
	})
}

// AddCreditsPer1kTokensInput adds v to the "credits_per_1k_tokens_input" field.
func (u *ModelCreditRateUpsertBulk) AddCreditsPer1kTokensInput(v int64) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.AddCreditsPer1kTokensInput(v)
	})
}

// UpdateCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field to the value that was provided on create.
func (u *ModelCreditRateUpsertBulk) UpdateCreditsPer1kTokensInput() *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateCreditsPer1kTokensInput()
	})
}

// SetCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field.
func (u *ModelCreditRateUpsertBulk) SetCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetCreditsPer1kTokensOutput(v)
	})
}

// AddCreditsPer1kTokensOutput adds v to the "credits_per_1k_tokens_output" field.
func (u *ModelCreditRateUpsertBulk) AddCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.AddCreditsPer1kTokensOutput(v)
	})
}

// UpdateCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field to the value that was provided on create.
func (u *ModelCreditRateUpsertBulk) UpdateCreditsPer1kTokensOutput() *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateCreditsPer1kTokensOutput()
	})
}

// SetPriority sets the "priority" field.
func (u *ModelCreditRateUpsertBulk) SetPriority(v int) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ModelCreditRateUpsertBulk) AddPriority(v int) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ModelCreditRateUpsertBulk) UpdatePriority() *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdatePriority()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCreditRateUpsertBulk) SetUpdatedAt(v time.Time) *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCreditRateUpsertBulk) UpdateUpdatedAt() *ModelCreditRateUpsertBulk {
	return u.Update(func(s *ModelCreditRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelCreditRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCreditRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCreditRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCreditRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
