// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcreditrate"
)

// ModelCreditRate is the model entity for the ModelCreditRate schema.
type ModelCreditRate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 模型匹配模式，支持 * 通配符，如 claude-opus-4*
	ModelPattern string `json:"model_pattern,omitempty"`
	// 每 1000 个输入 token 消耗的积分数
	CreditsPer1kTokensInput int64 `json:"credits_per_1k_tokens_input,omitempty"`
	// 每 1000 个输出 token 消耗的积分数
	CreditsPer1kTokensOutput int64 `json:"credits_per_1k_tokens_output,omitempty"`
	// 匹配优先级，值越大优先级越高
	Priority int `json:"priority,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCreditRate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcreditrate.FieldID, modelcreditrate.FieldCreditsPer1kTokensInput, modelcreditrate.FieldCreditsPer1kTokensOutput, modelcreditrate.FieldPriority:
			values[i] = new(sql.NullInt64)
		case modelcreditrate.FieldModelPattern:
			values[i] = new(sql.NullString)
		case modelcreditrate.FieldCreatedAt, modelcreditrate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCreditRate fields.
func (_m *ModelCreditRate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcreditrate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelcreditrate.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case modelcreditrate.FieldCreditsPer1kTokensInput:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credits_per_1k_tokens_input", values[i])
			} else if value.Valid {
				_m.CreditsPer1kTokensInput = value.Int64
			}
		case modelcreditrate.FieldCreditsPer1kTokensOutput:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credits_per_1k_tokens_output", values[i])
			} else if value.Valid {
				_m.CreditsPer1kTokensOutput = value.Int64
			}
		case modelcreditrate.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case modelcreditrate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcreditrate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCreditRate.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCreditRate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelCreditRate.
// Note that you need to call ModelCreditRate.Unwrap() before calling this method if this ModelCreditRate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCreditRate) Update() *ModelCreditRateUpdateOne {
	return NewModelCreditRateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCreditRate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCreditRate) Unwrap() *ModelCreditRate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCreditRate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCreditRate) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCreditRate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("credits_per_1k_tokens_input=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditsPer1kTokensInput))
	builder.WriteString(", ")
	builder.WriteString("credits_per_1k_tokens_output=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditsPer1kTokensOutput))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelCreditRates is a parsable slice of ModelCreditRate.
type ModelCreditRates []*ModelCreditRate
