// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcreditrate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCreditRateUpdate is the builder for updating ModelCreditRate entities.
type ModelCreditRateUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCreditRateMutation
}

// Where appends a list predicates to the ModelCreditRateUpdate builder.
func (_u *ModelCreditRateUpdate) Where(ps ...predicate.ModelCreditRate) *ModelCreditRateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *ModelCreditRateUpdate) SetModelPattern(v string) *ModelCreditRateUpdate {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *ModelCreditRateUpdate) SetNillableModelPattern(v *string) *ModelCreditRateUpdate {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field.
func (_u *ModelCreditRateUpdate) SetCreditsPer1kTokensInput(v int64) *ModelCreditRateUpdate {
	_u.mutation.ResetCreditsPer1kTokensInput()
	_u.mutation.SetCreditsPer1kTokensInput(v)
	return _u
}

// SetNillableCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field if the given value is not nil.
func (_u *ModelCreditRateUpdate) SetNillableCreditsPer1kTokensInput(v *int64) *ModelCreditRateUpdate {
	if v != nil {
		_u.SetCreditsPer1kTokensInput(*v)
	}
	return _u
}

// AddCreditsPer1kTokensInput adds value to the "credits_per_1k_tokens_input" field.
func (_u *ModelCreditRateUpdate) AddCreditsPer1kTokensInput(v int64) *ModelCreditRateUpdate {
	_u.mutation.AddCreditsPer1kTokensInput(v)
	return _u
}

// SetCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field.
func (_u *ModelCreditRateUpdate) SetCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpdate {
	_u.mutation.ResetCreditsPer1kTokensOutput()
	_u.mutation.SetCreditsPer1kTokensOutput(v)
	return _u
}

// SetNillableCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field if the given value is not nil.
func (_u *ModelCreditRateUpdate) SetNillableCreditsPer1kTokensOutput(v *int64) *ModelCreditRateUpdate {
	if v != nil {
		_u.SetCreditsPer1kTokensOutput(*v)
	}
	return _u
}

// AddCreditsPer1kTokensOutput adds value to the "credits_per_1k_tokens_output" field.
func (_u *ModelCreditRateUpdate) AddCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpdate {
	_u.mutation.AddCreditsPer1kTokensOutput(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ModelCreditRateUpdate) SetPriority(v int) *ModelCreditRateUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ModelCreditRateUpdate) SetNillablePriority(v *int) *ModelCreditRateUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ModelCreditRateUpdate) AddPriority(v int) *ModelCreditRateUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCreditRateUpdate) SetUpdatedAt(v time.Time) *ModelCreditRateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCreditRateMutation object of the builder.
func (_u *ModelCreditRateUpdate) Mutation() *ModelCreditRateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCreditRateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCreditRateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCreditRateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCreditRateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCreditRateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcreditrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCreditRateUpdate) check() error {
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := modelcreditrate.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelCreditRate.model_pattern": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCreditRateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcreditrate.Table, modelcreditrate.Columns, sqlgraph.NewFieldSpec(modelcreditrate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(modelcreditrate.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditsPer1kTokensInput(); ok {
		_spec.SetField(modelcreditrate.FieldCreditsPer1kTokensInput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditsPer1kTokensInput(); ok {
		_spec.AddField(modelcreditrate.FieldCreditsPer1kTokensInput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreditsPer1kTokensOutput(); ok {
		_spec.SetField(modelcreditrate.FieldCreditsPer1kTokensOutput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditsPer1kTokensOutput(); ok {
		_spec.AddField(modelcreditrate.FieldCreditsPer1kTokensOutput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(modelcreditrate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(modelcreditrate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcreditrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcreditrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCreditRateUpdateOne is the builder for updating a single ModelCreditRate entity.
type ModelCreditRateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCreditRateMutation
}

// SetModelPattern sets the "model_pattern" field.
func (_u *ModelCreditRateUpdateOne) SetModelPattern(v string) *ModelCreditRateUpdateOne {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *ModelCreditRateUpdateOne) SetNillableModelPattern(v *string) *ModelCreditRateUpdateOne {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field.
func (_u *ModelCreditRateUpdateOne) SetCreditsPer1kTokensInput(v int64) *ModelCreditRateUpdateOne {
	_u.mutation.ResetCreditsPer1kTokensInput()
	_u.mutation.SetCreditsPer1kTokensInput(v)
	return _u
}

// SetNillableCreditsPer1kTokensInput sets the "credits_per_1k_tokens_input" field if the given value is not nil.
func (_u *ModelCreditRateUpdateOne) SetNillableCreditsPer1kTokensInput(v *int64) *ModelCreditRateUpdateOne {
	if v != nil {
		_u.SetCreditsPer1kTokensInput(*v)
	}
	return _u
}

// AddCreditsPer1kTokensInput adds value to the "credits_per_1k_tokens_input" field.
func (_u *ModelCreditRateUpdateOne) AddCreditsPer1kTokensInput(v int64) *ModelCreditRateUpdateOne {
	_u.mutation.AddCreditsPer1kTokensInput(v)
	return _u
}

// SetCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field.
func (_u *ModelCreditRateUpdateOne) SetCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpdateOne {
	_u.mutation.ResetCreditsPer1kTokensOutput()
	_u.mutation.SetCreditsPer1kTokensOutput(v)
	return _u
}

// SetNillableCreditsPer1kTokensOutput sets the "credits_per_1k_tokens_output" field if the given value is not nil.
func (_u *ModelCreditRateUpdateOne) SetNillableCreditsPer1kTokensOutput(v *int64) *ModelCreditRateUpdateOne {
	if v != nil {
		_u.SetCreditsPer1kTokensOutput(*v)
	}
	return _u
}

// AddCreditsPer1kTokensOutput adds value to the "credits_per_1k_tokens_output" field.
func (_u *ModelCreditRateUpdateOne) AddCreditsPer1kTokensOutput(v int64) *ModelCreditRateUpdateOne {
	_u.mutation.AddCreditsPer1kTokensOutput(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ModelCreditRateUpdateOne) SetPriority(v int) *ModelCreditRateUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ModelCreditRateUpdateOne) SetNillablePriority(v *int) *ModelCreditRateUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ModelCreditRateUpdateOne) AddPriority(v int) *ModelCreditRateUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCreditRateUpdateOne) SetUpdatedAt(v time.Time) *ModelCreditRateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCreditRateMutation object of the builder.
func (_u *ModelCreditRateUpdateOne) Mutation() *ModelCreditRateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelCreditRateUpdate builder.
func (_u *ModelCreditRateUpdateOne) Where(ps ...predicate.ModelCreditRate) *ModelCreditRateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCreditRateUpdateOne) Select(field string, fields ...string) *ModelCreditRateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCreditRate entity.
func (_u *ModelCreditRateUpdateOne) Save(ctx context.Context) (*ModelCreditRate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCreditRateUpdateOne) SaveX(ctx context.Context) *ModelCreditRate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCreditRateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCreditRateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCreditRateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcreditrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCreditRateUpdateOne) check() error {
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := modelcreditrate.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelCreditRate.model_pattern": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCreditRateUpdateOne) sqlSave(ctx context.Context) (_node *ModelCreditRate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcreditrate.Table, modelcreditrate.Columns, sqlgraph.NewFieldSpec(modelcreditrate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCreditRate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcreditrate.FieldID)
		for _, f := range fields {
			if !modelcreditrate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcreditrate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(modelcreditrate.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditsPer1kTokensInput(); ok {
		_spec.SetField(modelcreditrate.FieldCreditsPer1kTokensInput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditsPer1kTokensInput(); ok {
		_spec.AddField(modelcreditrate.FieldCreditsPer1kTokensInput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreditsPer1kTokensOutput(); ok {
		_spec.SetField(modelcreditrate.FieldCreditsPer1kTokensOutput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditsPer1kTokensOutput(); ok {
		_spec.AddField(modelcreditrate.FieldCreditsPer1kTokensOutput, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(modelcreditrate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(modelcreditrate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcreditrate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelCreditRate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcreditrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
