// Code generated by ent, DO NOT EDIT.

package creditledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldUserID, v))
}

// Delta applies equality check predicate on the "delta" field. It's identical to DeltaEQ.
func Delta(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldDelta, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldReason, v))
}

// RefID applies equality check predicate on the "ref_id" field. It's identical to RefIDEQ.
func RefID(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldRefID, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldModel, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldUserID, v))
}

// DeltaEQ applies the EQ predicate on the "delta" field.
func DeltaEQ(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldDelta, v))
}

// DeltaNEQ applies the NEQ predicate on the "delta" field.
func DeltaNEQ(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldDelta, v))
}

// DeltaIn applies the In predicate on the "delta" field.
func DeltaIn(vs ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldDelta, vs...))
}

// DeltaNotIn applies the NotIn predicate on the "delta" field.
func DeltaNotIn(vs ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldDelta, vs...))
}

// DeltaGT applies the GT predicate on the "delta" field.
func DeltaGT(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldDelta, v))
}

// DeltaGTE applies the GTE predicate on the "delta" field.
func DeltaGTE(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldDelta, v))
}

// DeltaLT applies the LT predicate on the "delta" field.
func DeltaLT(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldDelta, v))
}

// DeltaLTE applies the LTE predicate on the "delta" field.
func DeltaLTE(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldDelta, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContainsFold(FieldReason, v))
}

// RefIDEQ applies the EQ predicate on the "ref_id" field.
func RefIDEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldRefID, v))
}

// RefIDNEQ applies the NEQ predicate on the "ref_id" field.
func RefIDNEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldRefID, v))
}

// RefIDIn applies the In predicate on the "ref_id" field.
func RefIDIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldRefID, vs...))
}

// RefIDNotIn applies the NotIn predicate on the "ref_id" field.
func RefIDNotIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldRefID, vs...))
}

// RefIDGT applies the GT predicate on the "ref_id" field.
func RefIDGT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldRefID, v))
}

// RefIDGTE applies the GTE predicate on the "ref_id" field.
func RefIDGTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldRefID, v))
}

// RefIDLT applies the LT predicate on the "ref_id" field.
func RefIDLT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldRefID, v))
}

// RefIDLTE applies the LTE predicate on the "ref_id" field.
func RefIDLTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldRefID, v))
}

// RefIDContains applies the Contains predicate on the "ref_id" field.
func RefIDContains(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContains(FieldRefID, v))
}

// RefIDHasPrefix applies the HasPrefix predicate on the "ref_id" field.
func RefIDHasPrefix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasPrefix(FieldRefID, v))
}

// RefIDHasSuffix applies the HasSuffix predicate on the "ref_id" field.
func RefIDHasSuffix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasSuffix(FieldRefID, v))
}

// RefIDIsNil applies the IsNil predicate on the "ref_id" field.
func RefIDIsNil() predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIsNull(FieldRefID))
}

// RefIDNotNil applies the NotNil predicate on the "ref_id" field.
func RefIDNotNil() predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotNull(FieldRefID))
}

// RefIDEqualFold applies the EqualFold predicate on the "ref_id" field.
func RefIDEqualFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEqualFold(FieldRefID, v))
}

// RefIDContainsFold applies the ContainsFold predicate on the "ref_id" field.
func RefIDContainsFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContainsFold(FieldRefID, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v int64) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldBalanceAfter, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContainsFold(FieldModel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreditLedger) predicate.CreditLedger {
	return predicate.CreditLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreditLedger) predicate.CreditLedger {
	return predicate.CreditLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreditLedger) predicate.CreditLedger {
	return predicate.CreditLedger(sql.NotPredicates(p))
}
